// ============================================================================
// IVOIREAPPRO ERP — DONNÉES DE SEED FICTIVES RÉALISTES (CÔTE D'IVOIRE)
// Date de référence : 2026-10-07
// Conformité stricte Sections 1, 40 & 41 :
// - Aucune donnée militaire sensible ni coordonnée réelle.
// - Séparation explicite des règles internes, contractuelles, administratives,
//   fiscales et documentaires configurables.
// ============================================================================

import {
  AuditActionType,
  ContractStatus,
  DeliveryStatus,
  DocumentStatus,
  DocumentType,
  ErpState,
  ExpenseCategoryType,
  InvoiceStatus,
  RoleName,
  RuleCategory,
  StockMovementType,
  TaxCertificationStatus,
  UnitCode,
} from './types';

export const INITIAL_ERP_STATE: ErpState = {
  organization: {
    id: 'org-sogepro-ci',
    legalName: 'Société Générale d’Approvisionnement Vivrier de Côte d’Ivoire SARL (Entité Fictive)',
    tradeName: 'SOGEPRO-CI Distribution',
    taxId: 'CI-ABJ-FICTIF-2021-B-10492',
    registrationNumber: 'RCCM-CI-ABJ-03-2021-B12-00492 (Fictif)',
    address: 'Zone Industrielle de Yopougon, Lot 114, Abidjan — Côte d’Ivoire',
    phone: '+225 27 23 45 00 00',
    email: 'direction@sogepro-ci-demo.example',
    currency: 'XOF',
  },
  currentUserId: 'usr-owner-01',
  users: [
    {
      id: 'usr-owner-01',
      organizationId: 'org-sogepro-ci',
      name: 'Kouamé Jean-Baptiste',
      email: 'jb.kouame@sogepro-ci-demo.example',
      phone: '+225 07 08 11 22 33',
      role: RoleName.OWNER,
      roleLabel: 'Direction Générale (Owner)',
      permissions: [
        'contracts:write',
        'orders:write',
        'deliveries:write',
        'deliveries:validate',
        'deliveries:override_quota',
        'receptions:write',
        'inventory:write',
        'finance:write',
        'documents:finalize',
        'settings:write',
      ],
      isActive: true,
      lastLoginAt: '2026-10-07 08:15',
    },
    {
      id: 'usr-manager-02',
      organizationId: 'org-sogepro-ci',
      name: 'Koné Aminata',
      email: 'a.kone@sogepro-ci-demo.example',
      phone: '+225 07 09 44 55 66',
      role: RoleName.MANAGER,
      roleLabel: 'Directrice des Opérations',
      permissions: [
        'contracts:write',
        'orders:write',
        'deliveries:write',
        'deliveries:validate',
        'deliveries:override_quota',
        'receptions:write',
        'inventory:write',
        'documents:finalize',
      ],
      isActive: true,
      lastLoginAt: '2026-10-07 07:50',
    },
    {
      id: 'usr-logistics-03',
      organizationId: 'org-sogepro-ci',
      name: 'Bamba Souleymane',
      email: 's.bamba@sogepro-ci-demo.example',
      phone: '+225 05 04 33 21 10',
      role: RoleName.LOGISTICS,
      roleLabel: 'Coordinateur Logistique & Flotte',
      permissions: [
        'deliveries:write',
        'deliveries:validate',
        'receptions:write',
        'documents:finalize',
      ],
      isActive: true,
      lastLoginAt: '2026-10-07 06:40',
    },
    {
      id: 'usr-warehouse-04',
      organizationId: 'org-sogepro-ci',
      name: 'Yao Franck Olivier',
      email: 'f.yao@sogepro-ci-demo.example',
      phone: '+225 01 02 88 77 66',
      role: RoleName.WAREHOUSE,
      roleLabel: 'Chef Magasinier Entrepôt Central',
      permissions: ['inventory:write', 'deliveries:write'],
      isActive: true,
      lastLoginAt: '2026-10-07 06:15',
    },
    {
      id: 'usr-accounting-05',
      organizationId: 'org-sogepro-ci',
      name: 'N’Guessan Clarisse',
      email: 'c.nguessan@sogepro-ci-demo.example',
      phone: '+225 07 55 66 77 88',
      role: RoleName.ACCOUNTING,
      roleLabel: 'Chef Comptable & Recouvrement',
      permissions: ['finance:write', 'documents:finalize'],
      isActive: true,
      lastLoginAt: '2026-10-07 08:05',
    },
    {
      id: 'usr-viewer-06',
      organizationId: 'org-sogepro-ci',
      name: 'Touré Ibrahim',
      email: 'i.toure@sogepro-ci-demo.example',
      phone: '+225 07 11 00 99 88',
      role: RoleName.VIEWER,
      roleLabel: 'Contrôleur de Gestion (Lecture seule)',
      permissions: [],
      isActive: true,
      lastLoginAt: '2026-10-06 17:30',
    },
  ],
  customers: [
    {
      id: 'cust-chu-nord',
      organizationId: 'org-sogepro-ci',
      code: 'CLI-INST-001',
      name: 'Groupement Hospitalier Universitaire Lagunes (Organisme Fictif)',
      category: 'Santé Publique & Restauration Hospitalière',
      taxIdentifier: 'ID-FISC-DEMO-CHU-01',
      paymentTermsDays: 45,
      primaryContactName: 'Dr. Aka Marie-Louise',
      primaryContactRole: 'Intendante Générale des Services Économiques',
      primaryContactPhone: '+225 27 22 40 10 10',
      primaryContactEmail: 'intendance@ghu-lagunes-demo.example',
      destinations: [
        {
          id: 'dest-chu-cocody',
          customerId: 'cust-chu-nord',
          siteName: 'Site Hospitalier Central — Magasin Vivres Cocody (Fictif)',
          city: 'Abidjan - Cocody',
          addressLine: 'Boulevard de l’Université, Quai de Réception Bâtiment C',
          receivingHours: '07h30 - 14h30 (Paramètre administratif client)',
          requiredDocTypes: ['Bordereau de livraison signé', 'Certificat qualité lot'],
          contactPerson: 'M. Koffi Pacôme (Chef Économe)',
          contactPhone: '+225 07 44 12 01 01',
        },
        {
          id: 'dest-chu-anyama',
          customerId: 'cust-chu-nord',
          siteName: 'Annexe Régionale Nord — Économat Anyama (Fictif)',
          city: 'Anyama',
          addressLine: 'Voie Express Nord, Entrée Logistique Sud',
          receivingHours: '08h00 - 15h00 (Paramètre administratif client)',
          requiredDocTypes: ['Bordereau de livraison signé', 'Bon de commande visé'],
          contactPerson: 'Mme Diomandé Salimata',
          contactPhone: '+225 05 55 89 12 34',
        },
      ],
    },
    {
      id: 'cust-crous-ci',
      organizationId: 'org-sogepro-ci',
      code: 'CLI-INST-002',
      name: 'Office Régional des Cantines & Internats Universitaires (Organisme Fictif)',
      category: 'Enseignement Supérieur & Restauration Collective',
      taxIdentifier: 'ID-FISC-DEMO-ORCIU-02',
      paymentTermsDays: 60,
      primaryContactName: 'M. Soro Seydou',
      primaryContactRole: 'Directeur des Approvisionnements',
      primaryContactPhone: '+225 27 30 64 00 11',
      primaryContactEmail: 'appro@orciu-demo.example',
      destinations: [
        {
          id: 'dest-campus-abj',
          customerId: 'cust-crous-ci',
          siteName: 'Restauration Centrale Campus Sud (Fictif)',
          city: 'Abidjan - Plateau / Adjamé',
          addressLine: 'Avenue des Grandes Écoles, Entrepôt Frigorifique & Sec',
          receivingHours: '06h30 - 13h00 (Paramètre administratif client)',
          requiredDocTypes: ['Bordereau de livraison en 3 exemplaires', 'Fiche de pesée'],
          contactPerson: 'M. Brou Célestin',
          contactPhone: '+225 07 01 23 45 67',
        },
        {
          id: 'dest-campus-yamoussoukro',
          customerId: 'cust-crous-ci',
          siteName: 'Complexe Universitaire des Lacs — Yamoussoukro (Fictif)',
          city: 'Yamoussoukro',
          addressLine: 'Zone Académique Nord, Magasin Général Vivres',
          receivingHours: '07h30 - 16h00 (Paramètre administratif client)',
          requiredDocTypes: ['Bordereau de livraison signé', 'PV de réception contradictoire'],
          contactPerson: 'M. Kra Kouadio',
          contactPhone: '+225 07 88 99 11 22',
        },
      ],
    },
    {
      id: 'cust-collectivite-sud',
      organizationId: 'org-sogepro-ci',
      code: 'CLI-INST-003',
      name: 'Direction Centrale de l’Action Sociale & Solidarité (Organisme Fictif)',
      category: 'Administration & Centres Sociaux',
      taxIdentifier: 'ID-FISC-DEMO-DCASS-03',
      paymentTermsDays: 30,
      primaryContactName: 'Mme Bictogo Nadège',
      primaryContactRole: 'Coordinatrice Logistique Programmes Alimentaires',
      primaryContactPhone: '+225 27 20 21 90 00',
      primaryContactEmail: 'logistique@dcass-demo.example',
      destinations: [
        {
          id: 'dest-centre-bouake',
          customerId: 'cust-collectivite-sud',
          siteName: 'Plateforme Régionale de Distribution — Bouaké (Fictif)',
          city: 'Bouaké',
          addressLine: 'Quartier Commerce, Entrepôt Régional N°4',
          receivingHours: '08h00 - 17h00 (Paramètre administratif client)',
          requiredDocTypes: ['Bordereau de livraison signé'],
          contactPerson: 'M. Ouattara Dramane',
          contactPhone: '+225 07 66 55 44 33',
        },
      ],
    },
  ],
  products: [
    {
      id: 'prod-riz-50',
      organizationId: 'org-sogepro-ci',
      reference: 'DEN-RIZ-001',
      internalCode: 'RZ-LG-50K',
      name: 'Riz Blanc Long Grain Parfumé (Qualité Supérieure)',
      categoryName: 'Céréales & Grains',
      unit: UnitCode.KG,
      weightKg: 1,
      packaging: 'Conditionné en sacs polypropylène de 50 KG',
      conversionToKg: 1,
      conversionRuleLabel: '1 SAC = 50 KG | 1 TONNE = 1 000 KG (20 Sacs)',
      standardCost: 410,
      minStockThreshold: 8000,
      isActive: true,
    },
    {
      id: 'prod-huile-20l',
      organizationId: 'org-sogepro-ci',
      reference: 'DEN-HUI-002',
      internalCode: 'HL-PALM-20L',
      name: 'Huile Végétale Raffinée Enrichie en Vitamine A',
      categoryName: 'Corps Gras & Huiles',
      unit: UnitCode.LITER,
      weightKg: 0.92,
      packaging: 'Bidon scellé alimentaire de 20 Litres',
      conversionToKg: 0.92,
      conversionRuleLabel: '1 BIDON = 20 LITRES (18,4 KG net)',
      standardCost: 920,
      minStockThreshold: 2500,
      isActive: true,
    },
    {
      id: 'prod-sucre-50',
      organizationId: 'org-sogepro-ci',
      reference: 'DEN-SUC-003',
      internalCode: 'SC-ROUX-50K',
      name: 'Sucre Cristallisé Roux de Canne Local',
      categoryName: 'Épicerie Seche',
      unit: UnitCode.KG,
      weightKg: 1,
      packaging: 'Sac doublé PEHD de 50 KG',
      conversionToKg: 1,
      conversionRuleLabel: '1 SAC = 50 KG',
      standardCost: 590,
      minStockThreshold: 3000,
      isActive: true,
    },
    {
      id: 'prod-haricot-50',
      organizationId: 'org-sogepro-ci',
      reference: 'DEN-LEG-004',
      internalCode: 'HR-BLC-50K',
      name: 'Haricot Blanc Sec Trié (Niébé Sélectionné)',
      categoryName: 'Légumineuses',
      unit: UnitCode.KG,
      weightKg: 1,
      packaging: 'Sac jute doublé de 50 KG',
      conversionToKg: 1,
      conversionRuleLabel: '1 SAC = 50 KG',
      standardCost: 680,
      minStockThreshold: 2000,
      isActive: true,
    },
    {
      id: 'prod-tomate-carton',
      organizationId: 'org-sogepro-ci',
      reference: 'DEN-CON-005',
      internalCode: 'TM-CONC-28',
      name: 'Double Concentré de Tomate 28/30% (Boîtes 2,2 KG)',
      categoryName: 'Conserves & Condiments',
      unit: UnitCode.CARTON,
      weightKg: 13.2,
      packaging: 'Carton de 6 boîtes métalliques de 2,2 KG (13,2 KG net)',
      conversionToKg: 13.2,
      conversionRuleLabel: '1 CARTON = 6 BOÎTES = 13,2 KG net',
      standardCost: 14800,
      minStockThreshold: 180,
      isActive: true,
    },
    {
      id: 'prod-lait-carton',
      organizationId: 'org-sogepro-ci',
      reference: 'DEN-LAI-006',
      internalCode: 'LT-PDR-25K',
      name: 'Lait Entier Instantané en Poudre Enrichi',
      categoryName: 'Produits Laitiers Secs',
      unit: UnitCode.KG,
      weightKg: 1,
      packaging: 'Sac papier kraft multi-plis 25 KG',
      conversionToKg: 1,
      conversionRuleLabel: '1 SAC = 25 KG',
      standardCost: 2350,
      minStockThreshold: 1200,
      isActive: true,
    },
  ],
  contracts: [
    {
      id: 'ctr-2026-chu-01',
      organizationId: 'org-sogepro-ci',
      reference: 'M-2026-GHU-014',
      title: 'Fourniture annuelle de denrées alimentaires sèches et huiles — GHU Lagunes',
      customerId: 'cust-chu-nord',
      startDate: '2026-01-15',
      endDate: '2026-12-31',
      status: ContractStatus.ACTIVE,
      currency: 'XOF',
      totalAmount: 42400000,
      notes:
        'Marché à commandes fractionnées sur 2 sites (Cocody & Anyama). Taux de taxe configuré à 0% (régime contractuel exonéré renseigné par le client).',
      lines: [
        {
          id: 'cline-101',
          contractId: 'ctr-2026-chu-01',
          productId: 'prod-riz-50',
          unit: UnitCode.KG,
          quantity: 40000,
          unitPrice: 560,
          taxRate: 0,
          totalAmount: 22400000,
        },
        {
          id: 'cline-102',
          contractId: 'ctr-2026-chu-01',
          productId: 'prod-huile-20l',
          unit: UnitCode.LITER,
          quantity: 10000,
          unitPrice: 1250,
          taxRate: 0,
          totalAmount: 12500000,
        },
        {
          id: 'cline-103',
          contractId: 'ctr-2026-chu-01',
          productId: 'prod-sucre-50',
          unit: UnitCode.KG,
          quantity: 10000,
          unitPrice: 750,
          taxRate: 0,
          totalAmount: 7500000,
        },
      ],
    },
    {
      id: 'ctr-2026-orciu-02',
      organizationId: 'org-sogepro-ci',
      reference: 'M-2026-UNIV-029',
      title: 'Approvisionnement des Restaurants Universitaires Abidjan & Yamoussoukro',
      customerId: 'cust-crous-ci',
      startDate: '2026-03-01',
      endDate: '2026-11-15',
      status: ContractStatus.ACTIVE,
      currency: 'XOF',
      totalAmount: 65100000,
      notes:
        'Livraisons mensuelles sur appel de commande. Échéance du marché proche (15 novembre 2026).',
      lines: [
        {
          id: 'cline-201',
          contractId: 'ctr-2026-orciu-02',
          productId: 'prod-riz-50',
          unit: UnitCode.KG,
          quantity: 60000,
          unitPrice: 550,
          taxRate: 0,
          totalAmount: 33000000,
        },
        {
          id: 'cline-202',
          contractId: 'ctr-2026-orciu-02',
          productId: 'prod-haricot-50',
          unit: UnitCode.KG,
          quantity: 20000,
          unitPrice: 920,
          taxRate: 0,
          totalAmount: 18400000,
        },
        {
          id: 'cline-203',
          contractId: 'ctr-2026-orciu-02',
          productId: 'prod-tomate-carton',
          unit: UnitCode.CARTON,
          quantity: 500,
          unitPrice: 19000,
          taxRate: 0,
          totalAmount: 9500000,
        },
        {
          id: 'cline-204',
          contractId: 'ctr-2026-orciu-02',
          productId: 'prod-lait-carton',
          unit: UnitCode.KG,
          quantity: 1400,
          unitPrice: 3000,
          taxRate: 0,
          totalAmount: 4200000,
        },
      ],
    },
    {
      id: 'ctr-2026-dcass-03',
      organizationId: 'org-sogepro-ci',
      reference: 'M-2026-SOC-008',
      title: 'Dotation trimestrielle vivres Centres Sociaux Région Centre (Bouaké)',
      customerId: 'cust-collectivite-sud',
      startDate: '2026-06-01',
      endDate: '2026-10-25',
      status: ContractStatus.ACTIVE,
      currency: 'XOF',
      totalAmount: 18900000,
      notes: 'Échéance contractuelle sous 18 jours (25 octobre 2026).',
      lines: [
        {
          id: 'cline-301',
          contractId: 'ctr-2026-dcass-03',
          productId: 'prod-riz-50',
          unit: UnitCode.KG,
          quantity: 20000,
          unitPrice: 570,
          taxRate: 0,
          totalAmount: 11400000,
        },
        {
          id: 'cline-302',
          contractId: 'ctr-2026-dcass-03',
          productId: 'prod-huile-20l',
          unit: UnitCode.LITER,
          quantity: 6000,
          unitPrice: 1250,
          taxRate: 0,
          totalAmount: 7500000,
        },
      ],
    },
  ],
  orders: [
    {
      id: 'ord-2026-001',
      organizationId: 'org-sogepro-ci',
      reference: 'CMD-2026-000038',
      contractId: 'ctr-2026-chu-01',
      destinationId: 'dest-chu-cocody',
      orderDate: '2026-09-10',
      requestedDate: '2026-09-18',
      status: 'FULFILLED',
      totalAmount: 14950000,
      notes: 'Dotation Septembre Site Central Cocody.',
    },
    {
      id: 'ord-2026-002',
      organizationId: 'org-sogepro-ci',
      reference: 'CMD-2026-000039',
      contractId: 'ctr-2026-orciu-02',
      destinationId: 'dest-campus-abj',
      orderDate: '2026-09-20',
      requestedDate: '2026-09-28',
      status: 'FULFILLED',
      totalAmount: 21520000,
      notes: 'Commande Rentrée Universitaire Campus Sud.',
    },
    {
      id: 'ord-2026-003',
      organizationId: 'org-sogepro-ci',
      reference: 'CMD-2026-000040',
      contractId: 'ctr-2026-chu-01',
      destinationId: 'dest-chu-anyama',
      orderDate: '2026-10-02',
      requestedDate: '2026-10-07',
      status: 'IN_PROGRESS',
      totalAmount: 8630000,
      notes: 'Livraison programmée aujourd’hui 07/10/2026 sur l’annexe Anyama.',
    },
    {
      id: 'ord-2026-004',
      organizationId: 'org-sogepro-ci',
      reference: 'CMD-2026-000041',
      contractId: 'ctr-2026-orciu-02',
      destinationId: 'dest-campus-yamoussoukro',
      orderDate: '2026-10-03',
      requestedDate: '2026-10-08',
      status: 'CONFIRMED',
      totalAmount: 13260000,
      notes: 'Livraison programmée demain 08/10/2026 pour Yamoussoukro.',
    },
    {
      id: 'ord-2026-005',
      organizationId: 'org-sogepro-ci',
      reference: 'CMD-2026-000042',
      contractId: 'ctr-2026-dcass-03',
      destinationId: 'dest-centre-bouake',
      orderDate: '2026-09-28',
      requestedDate: '2026-10-04',
      status: 'IN_PROGRESS',
      totalAmount: 10680000,
      notes: 'Convoi Bouaké en attente de départ (léger retard logistique).',
    },
  ],
  deliveries: [
    {
      id: 'del-2026-00124',
      organizationId: 'org-sogepro-ci',
      reference: 'BL-2026-000124',
      contractId: 'ctr-2026-chu-01',
      orderId: 'ord-2026-001',
      destinationId: 'dest-chu-cocody',
      plannedDate: '2026-09-18',
      actualDate: '2026-09-18',
      status: DeliveryStatus.RECEIVED,
      driverName: 'Kouassi Yao Bernard',
      vehiclePlate: '4821-KJ-01',
      responsibleUser: 'Bamba Souleymane',
      notes: 'Réception complète sans réserve par le Chef Économe.',
      lines: [
        {
          id: 'dline-1',
          deliveryId: 'del-2026-00124',
          contractLineId: 'cline-101',
          productId: 'prod-riz-50',
          lotNumber: 'LOT-RZ-2608-A',
          unit: UnitCode.KG,
          quantityPlanned: 15000,
          quantityDelivered: 15000,
          quantityAccepted: 15000,
          quantityRejected: 0,
          unitPrice: 560,
          observation: 'Conforme — Pesée contradictoire validée (300 sacs de 50 kg).',
        },
        {
          id: 'dline-2',
          deliveryId: 'del-2026-00124',
          contractLineId: 'cline-102',
          productId: 'prod-huile-20l',
          lotNumber: 'LOT-HL-2607-B',
          unit: UnitCode.LITER,
          quantityPlanned: 3400,
          quantityDelivered: 3400,
          quantityAccepted: 3400,
          quantityRejected: 0,
          unitPrice: 1250,
          observation: '170 bidons de 20L scellés intacts.',
        },
        {
          id: 'dline-3',
          deliveryId: 'del-2026-00124',
          contractLineId: 'cline-103',
          productId: 'prod-sucre-50',
          lotNumber: 'LOT-SC-2608-A',
          unit: UnitCode.KG,
          quantityPlanned: 3000,
          quantityDelivered: 3000,
          quantityAccepted: 3000,
          quantityRejected: 0,
          unitPrice: 750,
          observation: '60 sacs de 50 kg acceptés.',
        },
      ],
      statusHistory: [
        {
          id: 'sh-1',
          status: DeliveryStatus.PLANNED,
          changedBy: 'Bamba Souleymane',
          comment: 'Dossier de livraison créé sur commande CMD-2026-000038',
          changedAt: '2026-09-16 10:15',
        },
        {
          id: 'sh-2',
          status: DeliveryStatus.READY,
          changedBy: 'Yao Franck Olivier',
          comment: 'Lots préparés et pesés au magasin central',
          changedAt: '2026-09-17 16:40',
        },
        {
          id: 'sh-3',
          status: DeliveryStatus.DISPATCHED,
          changedBy: 'Bamba Souleymane',
          comment: 'Bordereau BL-2026-000124 généré et camion expédié',
          changedAt: '2026-09-18 07:30',
        },
        {
          id: 'sh-4',
          status: DeliveryStatus.RECEIVED,
          changedBy: 'Bamba Souleymane',
          comment: 'Réception complète validée sur PV contradictoire signé',
          changedAt: '2026-09-18 11:45',
        },
      ],
    },
    {
      id: 'del-2026-00125',
      organizationId: 'org-sogepro-ci',
      reference: 'BL-2026-000125',
      contractId: 'ctr-2026-orciu-02',
      orderId: 'ord-2026-002',
      destinationId: 'dest-campus-abj',
      plannedDate: '2026-09-28',
      actualDate: '2026-09-28',
      status: DeliveryStatus.PARTIALLY_RECEIVED,
      driverName: 'Zadi Jean-Marc',
      vehiclePlate: '9104-GT-01',
      responsibleUser: 'Bamba Souleymane',
      notes:
        'Réception partielle avec réserve : 8 sacs de haricot blanc (400 KG) refusés pour humidité sur coutures.',
      lines: [
        {
          id: 'dline-4',
          deliveryId: 'del-2026-00125',
          contractLineId: 'cline-201',
          productId: 'prod-riz-50',
          lotNumber: 'LOT-RZ-2608-A',
          unit: UnitCode.KG,
          quantityPlanned: 22000,
          quantityDelivered: 22000,
          quantityAccepted: 22000,
          quantityRejected: 0,
          unitPrice: 550,
          observation: '440 sacs de 50 kg acceptés sans réserve.',
        },
        {
          id: 'dline-5',
          deliveryId: 'del-2026-00125',
          contractLineId: 'cline-202',
          productId: 'prod-haricot-50',
          lotNumber: 'LOT-HR-2607-C',
          unit: UnitCode.KG,
          quantityPlanned: 6000,
          quantityDelivered: 6000,
          quantityAccepted: 5600,
          quantityRejected: 400,
          unitPrice: 920,
          rejectionReason: 'Humidité constatée sur 8 sacs en fond de plateau',
          observation: '5 600 KG acceptés / 400 KG retournés à l’entrepôt pour tri.',
        },
        {
          id: 'dline-6',
          deliveryId: 'del-2026-00125',
          contractLineId: 'cline-203',
          productId: 'prod-tomate-carton',
          lotNumber: 'LOT-TM-2606-A',
          unit: UnitCode.CARTON,
          quantityPlanned: 200,
          quantityDelivered: 200,
          quantityAccepted: 200,
          quantityRejected: 0,
          unitPrice: 19000,
          observation: '200 cartons intacts acceptés.',
        },
      ],
      statusHistory: [
        {
          id: 'sh-5',
          status: DeliveryStatus.PLANNED,
          changedBy: 'Bamba Souleymane',
          comment: 'Planification livraison Campus Sud',
          changedAt: '2026-09-25 09:00',
        },
        {
          id: 'sh-6',
          status: DeliveryStatus.DISPATCHED,
          changedBy: 'Bamba Souleymane',
          comment: 'Départ camion 9104-GT-01',
          changedAt: '2026-09-28 06:45',
        },
        {
          id: 'sh-7',
          status: DeliveryStatus.PARTIALLY_RECEIVED,
          changedBy: 'Koné Aminata',
          comment: 'Réception enregistrée avec réserve sur 400 KG de Haricot Blanc',
          changedAt: '2026-09-28 13:20',
        },
      ],
    },
    {
      id: 'del-2026-00126',
      organizationId: 'org-sogepro-ci',
      reference: 'BL-2026-000126',
      contractId: 'ctr-2026-chu-01',
      orderId: 'ord-2026-003',
      destinationId: 'dest-chu-anyama',
      plannedDate: '2026-10-07',
      status: DeliveryStatus.DISPATCHED,
      driverName: 'Kouassi Yao Bernard',
      vehiclePlate: '4821-KJ-01',
      responsibleUser: 'Bamba Souleymane',
      notes: 'Livraison du jour en cours d’acheminement vers l’Annexe Nord Anyama.',
      lines: [
        {
          id: 'dline-7',
          deliveryId: 'del-2026-00126',
          contractLineId: 'cline-101',
          productId: 'prod-riz-50',
          lotNumber: 'LOT-RZ-2609-B',
          unit: UnitCode.KG,
          quantityPlanned: 8000,
          quantityDelivered: 8000,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 560,
        },
        {
          id: 'dline-8',
          deliveryId: 'del-2026-00126',
          contractLineId: 'cline-102',
          productId: 'prod-huile-20l',
          lotNumber: 'LOT-HL-2607-B',
          unit: UnitCode.LITER,
          quantityPlanned: 2120,
          quantityDelivered: 2120,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 1250,
        },
        {
          id: 'dline-9',
          deliveryId: 'del-2026-00126',
          contractLineId: 'cline-103',
          productId: 'prod-sucre-50',
          lotNumber: 'LOT-SC-2608-A',
          unit: UnitCode.KG,
          quantityPlanned: 2000,
          quantityDelivered: 2000,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 750,
        },
      ],
      statusHistory: [
        {
          id: 'sh-8',
          status: DeliveryStatus.PLANNED,
          changedBy: 'Bamba Souleymane',
          comment: 'Planifiée pour le 07/10/2026',
          changedAt: '2026-10-04 14:10',
        },
        {
          id: 'sh-9',
          status: DeliveryStatus.READY,
          changedBy: 'Yao Franck Olivier',
          comment: 'Chargement vérifié sur quai N°2',
          changedAt: '2026-10-06 17:45',
        },
        {
          id: 'sh-10',
          status: DeliveryStatus.DISPATCHED,
          changedBy: 'Bamba Souleymane',
          comment: 'Camion en route vers Anyama — En attente de réception sur site',
          changedAt: '2026-10-07 07:10',
        },
      ],
    },
    {
      id: 'del-2026-00127',
      organizationId: 'org-sogepro-ci',
      reference: 'BL-2026-000127',
      contractId: 'ctr-2026-orciu-02',
      orderId: 'ord-2026-004',
      destinationId: 'dest-campus-yamoussoukro',
      plannedDate: '2026-10-08',
      status: DeliveryStatus.PREPARING,
      driverName: 'Coulibaly Adama',
      vehiclePlate: '7732-LL-01',
      responsibleUser: 'Yao Franck Olivier',
      notes: 'Préparation en cours à l’entrepôt de Yopougon pour départ demain matin 05h30.',
      lines: [
        {
          id: 'dline-10',
          deliveryId: 'del-2026-00127',
          contractLineId: 'cline-201',
          productId: 'prod-riz-50',
          lotNumber: 'LOT-RZ-2609-B',
          unit: UnitCode.KG,
          quantityPlanned: 14000,
          quantityDelivered: 14000,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 550,
        },
        {
          id: 'dline-11',
          deliveryId: 'del-2026-00127',
          contractLineId: 'cline-202',
          productId: 'prod-haricot-50',
          lotNumber: 'LOT-HR-2607-C',
          unit: UnitCode.KG,
          quantityPlanned: 4000,
          quantityDelivered: 4000,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 920,
        },
        {
          id: 'dline-12',
          deliveryId: 'del-2026-00127',
          contractLineId: 'cline-204',
          productId: 'prod-lait-carton',
          lotNumber: 'LOT-LT-2605-A',
          unit: UnitCode.KG,
          quantityPlanned: 625,
          quantityDelivered: 625,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 3000,
        },
      ],
      statusHistory: [
        {
          id: 'sh-11',
          status: DeliveryStatus.PLANNED,
          changedBy: 'Bamba Souleymane',
          comment: 'Livraison programmée pour le 08/10/2026',
          changedAt: '2026-10-05 11:00',
        },
        {
          id: 'sh-12',
          status: DeliveryStatus.PREPARING,
          changedBy: 'Yao Franck Olivier',
          comment: 'Palettisation en cours au magasin central',
          changedAt: '2026-10-07 08:00',
        },
      ],
    },
    {
      id: 'del-2026-00128',
      organizationId: 'org-sogepro-ci',
      reference: 'BL-2026-000128',
      contractId: 'ctr-2026-dcass-03',
      orderId: 'ord-2026-005',
      destinationId: 'dest-centre-bouake',
      plannedDate: '2026-10-04',
      status: DeliveryStatus.READY,
      driverName: 'Zadi Jean-Marc',
      vehiclePlate: '9104-GT-01',
      responsibleUser: 'Bamba Souleymane',
      notes:
        'Alerte retard (3 jours) : Camion immobilisé pour révision freinage, départ reprogrammé ce soir.',
      lines: [
        {
          id: 'dline-13',
          deliveryId: 'del-2026-00128',
          contractLineId: 'cline-301',
          productId: 'prod-riz-50',
          lotNumber: 'LOT-RZ-2609-B',
          unit: UnitCode.KG,
          quantityPlanned: 12000,
          quantityDelivered: 12000,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 570,
        },
        {
          id: 'dline-14',
          deliveryId: 'del-2026-00128',
          contractLineId: 'cline-302',
          productId: 'prod-huile-20l',
          lotNumber: 'LOT-HL-2607-B',
          unit: UnitCode.LITER,
          quantityPlanned: 3000,
          quantityDelivered: 3000,
          quantityAccepted: 0,
          quantityRejected: 0,
          unitPrice: 1250,
        },
      ],
      statusHistory: [
        {
          id: 'sh-13',
          status: DeliveryStatus.PLANNED,
          changedBy: 'Bamba Souleymane',
          comment: 'Planifiée initialement le 04/10/2026',
          changedAt: '2026-10-01 09:30',
        },
        {
          id: 'sh-14',
          status: DeliveryStatus.READY,
          changedBy: 'Yao Franck Olivier',
          comment: 'Marchandise prête sur quai — attente tracteur routier',
          changedAt: '2026-10-04 15:00',
        },
      ],
    },
  ],
  warehouses: [
    {
      id: 'wh-abj-yop',
      organizationId: 'org-sogepro-ci',
      code: 'ENT-ABJ-01',
      name: 'Entrepôt Central Yopougon Zone Industrielle',
      location: 'Abidjan - Yopougon ZI',
      managerName: 'Yao Franck Olivier',
    },
    {
      id: 'wh-yakro-02',
      organizationId: 'org-sogepro-ci',
      code: 'ENT-YAK-02',
      name: 'Dépôt Transit Relais Yamoussoukro',
      location: 'Yamoussoukro Zone Nord',
      managerName: 'Koffi Arsène',
    },
  ],
  stockLots: [
    {
      id: 'lot-rz-01',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-riz-50',
      lotNumber: 'LOT-RZ-2608-A',
      receivedDate: '2026-08-12',
      expiryDate: '2027-08-12',
      unitCost: 405,
      initialQuantity: 50000,
      reservedQuantity: 0,
    },
    {
      id: 'lot-rz-02',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-riz-50',
      lotNumber: 'LOT-RZ-2609-B',
      receivedDate: '2026-09-19',
      expiryDate: '2027-09-19',
      unitCost: 415,
      initialQuantity: 45000,
      reservedQuantity: 26000,
    },
    {
      id: 'lot-hl-01',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-huile-20l',
      lotNumber: 'LOT-HL-2607-B',
      receivedDate: '2026-07-10',
      expiryDate: '2027-04-10',
      unitCost: 920,
      initialQuantity: 14000,
      reservedQuantity: 3000,
    },
    {
      id: 'lot-sc-01',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-sucre-50',
      lotNumber: 'LOT-SC-2608-A',
      receivedDate: '2026-08-05',
      expiryDate: '2028-02-05',
      unitCost: 590,
      initialQuantity: 12000,
      reservedQuantity: 0,
    },
    {
      id: 'lot-hr-01',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-haricot-50',
      lotNumber: 'LOT-HR-2607-C',
      receivedDate: '2026-07-22',
      expiryDate: '2027-03-20',
      unitCost: 680,
      initialQuantity: 14000,
      reservedQuantity: 4000,
    },
    {
      id: 'lot-tm-01',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-tomate-carton',
      lotNumber: 'LOT-TM-2606-A',
      receivedDate: '2026-06-01',
      expiryDate: '2026-11-02', // Péremption proche (< 30 jours) pour alerte !
      unitCost: 14800,
      initialQuantity: 350,
      reservedQuantity: 0,
    },
    {
      id: 'lot-lt-01',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-lait-carton',
      lotNumber: 'LOT-LT-2605-A',
      receivedDate: '2026-05-15',
      expiryDate: '2026-10-28', // Péremption proche & stock critique !
      unitCost: 2350,
      initialQuantity: 950,
      reservedQuantity: 625,
    },
  ],
  stockMovements: [
    {
      id: 'mov-01',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-riz-50',
      lotId: 'lot-rz-01',
      lotNumber: 'LOT-RZ-2608-A',
      type: StockMovementType.RECEIPT,
      quantityDelta: 50000,
      referenceDoc: 'ACH-2026-000012',
      reason: 'Réception achat Importateur Port d’Abidjan (1 000 sacs de 50 kg)',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-08-12 10:00',
    },
    {
      id: 'mov-02',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-riz-50',
      lotId: 'lot-rz-02',
      lotNumber: 'LOT-RZ-2609-B',
      type: StockMovementType.RECEIPT,
      quantityDelta: 45000,
      referenceDoc: 'ACH-2026-000018',
      reason: 'Réception achat Coopérative Rizicole Gagnoa / Import (900 sacs)',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-19 14:30',
    },
    {
      id: 'mov-03',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-riz-50',
      lotId: 'lot-rz-01',
      lotNumber: 'LOT-RZ-2608-A',
      type: StockMovementType.DELIVERY,
      quantityDelta: -15000,
      referenceDoc: 'BL-2026-000124',
      reason: 'Sortie pour livraison GHU Lagunes Cocody',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-18 07:00',
    },
    {
      id: 'mov-04',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-riz-50',
      lotId: 'lot-rz-01',
      lotNumber: 'LOT-RZ-2608-A',
      type: StockMovementType.DELIVERY,
      quantityDelta: -22000,
      referenceDoc: 'BL-2026-000125',
      reason: 'Sortie pour livraison Campus Sud Abidjan',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-28 06:30',
    },
    {
      id: 'mov-05',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-riz-50',
      lotId: 'lot-rz-02',
      lotNumber: 'LOT-RZ-2609-B',
      type: StockMovementType.DELIVERY,
      quantityDelta: -8000,
      referenceDoc: 'BL-2026-000126',
      reason: 'Sortie pour livraison GHU Annexe Anyama',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-10-07 06:50',
    },
    {
      id: 'mov-06',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-huile-20l',
      lotId: 'lot-hl-01',
      lotNumber: 'LOT-HL-2607-B',
      type: StockMovementType.RECEIPT,
      quantityDelta: 14000,
      referenceDoc: 'ACH-2026-000014',
      reason: 'Entrée usine raffinerie Vridi (700 bidons de 20L)',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-07-10 11:20',
    },
    {
      id: 'mov-07',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-huile-20l',
      lotId: 'lot-hl-01',
      lotNumber: 'LOT-HL-2607-B',
      type: StockMovementType.DELIVERY,
      quantityDelta: -3400,
      referenceDoc: 'BL-2026-000124',
      reason: 'Sortie livraison GHU Cocody',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-18 07:00',
    },
    {
      id: 'mov-08',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-huile-20l',
      lotId: 'lot-hl-01',
      lotNumber: 'LOT-HL-2607-B',
      type: StockMovementType.DELIVERY,
      quantityDelta: -2120,
      referenceDoc: 'BL-2026-000126',
      reason: 'Sortie livraison GHU Anyama',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-10-07 06:50',
    },
    {
      id: 'mov-09',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-sucre-50',
      lotId: 'lot-sc-01',
      lotNumber: 'LOT-SC-2608-A',
      type: StockMovementType.RECEIPT,
      quantityDelta: 12000,
      referenceDoc: 'ACH-2026-000015',
      reason: 'Entrée Sucrerie Borotou/Zuenoula (240 sacs de 50 kg)',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-08-05 15:00',
    },
    {
      id: 'mov-10',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-sucre-50',
      lotId: 'lot-sc-01',
      lotNumber: 'LOT-SC-2608-A',
      type: StockMovementType.DELIVERY,
      quantityDelta: -3000,
      referenceDoc: 'BL-2026-000124',
      reason: 'Sortie livraison GHU Cocody',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-18 07:00',
    },
    {
      id: 'mov-11',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-sucre-50',
      lotId: 'lot-sc-01',
      lotNumber: 'LOT-SC-2608-A',
      type: StockMovementType.DELIVERY,
      quantityDelta: -2000,
      referenceDoc: 'BL-2026-000126',
      reason: 'Sortie livraison GHU Anyama',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-10-07 06:50',
    },
    {
      id: 'mov-12',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-haricot-50',
      lotId: 'lot-hr-01',
      lotNumber: 'LOT-HR-2607-C',
      type: StockMovementType.RECEIPT,
      quantityDelta: 14000,
      referenceDoc: 'ACH-2026-000016',
      reason: 'Réception Coopérative Vivrière Korhogo (280 sacs)',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-07-22 09:40',
    },
    {
      id: 'mov-13',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-haricot-50',
      lotId: 'lot-hr-01',
      lotNumber: 'LOT-HR-2607-C',
      type: StockMovementType.DELIVERY,
      quantityDelta: -6000,
      referenceDoc: 'BL-2026-000125',
      reason: 'Sortie livraison Campus Sud',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-28 06:30',
    },
    {
      id: 'mov-14',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-haricot-50',
      lotId: 'lot-hr-01',
      lotNumber: 'LOT-HR-2607-C',
      type: StockMovementType.RETURN,
      quantityDelta: 400,
      referenceDoc: 'BL-2026-000125-RET',
      reason: 'Retour de 8 sacs refusés à la réception Campus Sud (tri quarantaine)',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-28 16:10',
    },
    {
      id: 'mov-15',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-tomate-carton',
      lotId: 'lot-tm-01',
      lotNumber: 'LOT-TM-2606-A',
      type: StockMovementType.RECEIPT,
      quantityDelta: 350,
      referenceDoc: 'ACH-2026-000011',
      reason: 'Entrée 350 cartons Concentré de Tomate',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-06-01 10:00',
    },
    {
      id: 'mov-16',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-tomate-carton',
      lotId: 'lot-tm-01',
      lotNumber: 'LOT-TM-2606-A',
      type: StockMovementType.DELIVERY,
      quantityDelta: -200,
      referenceDoc: 'BL-2026-000125',
      reason: 'Sortie livraison Campus Sud',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-09-28 06:30',
    },
    {
      id: 'mov-17',
      organizationId: 'org-sogepro-ci',
      warehouseId: 'wh-abj-yop',
      productId: 'prod-lait-carton',
      lotId: 'lot-lt-01',
      lotNumber: 'LOT-LT-2605-A',
      type: StockMovementType.RECEIPT,
      quantityDelta: 950,
      referenceDoc: 'ACH-2026-000009',
      reason: 'Entrée Lait en poudre 38 sacs de 25 kg',
      performedBy: 'Yao Franck Olivier',
      createdAt: '2026-05-15 11:00',
    },
  ],
  suppliers: [
    {
      id: 'sup-01',
      organizationId: 'org-sogepro-ci',
      code: 'FRN-CI-01',
      name: 'Compagnie Ivoirienne des Grains & Céréales (Fictif)',
      specialty: 'Riz long grain, Maïs, Céréales en gros',
      phone: '+225 27 21 35 10 20',
      email: 'ventes@cigc-demo.example',
      city: 'Abidjan - Zone Portuaire Treichville',
    },
    {
      id: 'sup-02',
      organizationId: 'org-sogepro-ci',
      code: 'FRN-CI-02',
      name: 'Raffinerie Oléagineuse du Littoral SARL (Fictif)',
      specialty: 'Huiles végétales raffinées & Margarines',
      phone: '+225 27 21 27 88 99',
      email: 'commercial@rol-ci-demo.example',
      city: 'Abidjan - Zone Industrielle Vridi',
    },
    {
      id: 'sup-03',
      organizationId: 'org-sogepro-ci',
      code: 'FRN-CI-03',
      name: 'Union des Coopératives Vivrières du Nord (Fictif)',
      specialty: 'Légumineuses, Haricot Niébé, Produits locaux',
      phone: '+225 27 36 86 12 00',
      email: 'contact@ucvn-korhogo-demo.example',
      city: 'Korhogo',
    },
  ],
  purchaseOrders: [
    {
      id: 'po-2026-018',
      organizationId: 'org-sogepro-ci',
      reference: 'ACH-2026-000018',
      supplierId: 'sup-01',
      productId: 'prod-riz-50',
      quantity: 45000,
      unitCost: 415,
      totalAmount: 18675000,
      orderDate: '2026-09-12',
      expectedDate: '2026-09-19',
      status: 'PAID',
    },
    {
      id: 'po-2026-019',
      organizationId: 'org-sogepro-ci',
      reference: 'ACH-2026-000019',
      supplierId: 'sup-02',
      productId: 'prod-huile-20l',
      quantity: 8000,
      unitCost: 920,
      totalAmount: 7360000,
      orderDate: '2026-10-03',
      expectedDate: '2026-10-11',
      status: 'ORDERED',
    },
  ],
  documentTemplates: [
    {
      id: 'tpl-bl-v2',
      organizationId: 'org-sogepro-ci',
      code: 'TPL-BL-INST-2026',
      name: 'Bordereau de Livraison Institutionnel Contradictoire',
      type: DocumentType.DELIVERY_NOTE,
      version: 'v2.1-2026',
      status: 'ACTIVE',
      effectiveFrom: '2026-01-01',
      requiredSignatures: [
        'Visa Magasinier Départ',
        'Visa Chauffeur / Convoyeur',
        'Cachet & Signature Réceptionnaire Site Client',
      ],
      footerNotice:
        'Document généré à partir des données structurées validées. Toute réserve doit être mentionnée par ligne au moment de la réception contradictoire.',
    },
    {
      id: 'tpl-pv-v1',
      organizationId: 'org-sogepro-ci',
      code: 'TPL-PV-REC-2026',
      name: 'Procès-Verbal de Réception Quantitative & Qualitative',
      type: DocumentType.RECEIPT,
      version: 'v1.4-2026',
      status: 'ACTIVE',
      effectiveFrom: '2026-01-01',
      requiredSignatures: [
        'Représentant Fournisseur',
        'Économe / Commission de Réception Client',
      ],
      footerNotice:
        'Seules les quantités acceptées sur ce procès-verbal ouvrent droit à facturation définitive.',
    },
    {
      id: 'tpl-fac-v2',
      organizationId: 'org-sogepro-ci',
      code: 'TPL-FAC-COM-2026',
      name: 'Facture Commerciale Marché Institutionnel',
      type: DocumentType.INVOICE,
      version: 'v2.0-2026',
      status: 'ACTIVE',
      effectiveFrom: '2026-01-01',
      requiredSignatures: ['Direction Administrative & Financière'],
      footerNotice:
        'Facture établie conformément aux quantités réceptionnées et acceptées. Connecteur fiscal configurable.',
    },
  ],
  documents: [
    {
      id: 'doc-001',
      organizationId: 'org-sogepro-ci',
      entityType: 'CONTRACT',
      entityId: 'ctr-2026-chu-01',
      entityReference: 'M-2026-GHU-014',
      documentType: DocumentType.CONTRACT,
      title: 'Cahier des Clauses Contractuelles — Marché M-2026-GHU-014',
      fileName: 'Contrat_M-2026-GHU-014_Signe.pdf',
      mimeType: 'application/pdf',
      version: 1,
      status: DocumentStatus.FINAL,
      templateVersion: 'Contrat-Externe',
      checksum: 'SHA256:9F86D081884C7D659A2FEAA0C55AD015',
      uploadedBy: 'Kouamé Jean-Baptiste',
      createdAt: '2026-01-15 09:00',
    },
    {
      id: 'doc-002',
      organizationId: 'org-sogepro-ci',
      entityType: 'DELIVERY',
      entityId: 'del-2026-00124',
      entityReference: 'BL-2026-000124',
      documentType: DocumentType.DELIVERY_NOTE,
      title: 'Bordereau de Livraison BL-2026-000124 (Version Figée)',
      fileName: 'BL-2026-000124_v1_FINAL.pdf',
      mimeType: 'application/pdf',
      version: 1,
      status: DocumentStatus.FINAL,
      templateVersion: 'v2.1-2026',
      checksum: 'SHA256:4B227777D4DD1FC61C6F884F48641D02',
      uploadedBy: 'Bamba Souleymane',
      createdAt: '2026-09-18 07:25',
    },
    {
      id: 'doc-003',
      organizationId: 'org-sogepro-ci',
      entityType: 'DELIVERY',
      entityId: 'del-2026-00124',
      entityReference: 'BL-2026-000124',
      documentType: DocumentType.RECEIPT,
      title: 'PV de Réception Contradictoire Signé — BL-2026-000124',
      fileName: 'PV_Reception_BL-2026-000124_Signe.pdf',
      mimeType: 'application/pdf',
      version: 1,
      status: DocumentStatus.FINAL,
      templateVersion: 'v1.4-2026',
      checksum: 'SHA256:D4735E3A265E16EEE03F59718B9B5D03',
      uploadedBy: 'Bamba Souleymane',
      createdAt: '2026-09-18 12:00',
    },
    {
      id: 'doc-004',
      organizationId: 'org-sogepro-ci',
      entityType: 'DELIVERY',
      entityId: 'del-2026-00125',
      entityReference: 'BL-2026-000125',
      documentType: DocumentType.DELIVERY_NOTE,
      title: 'Bordereau de Livraison Rectificatif après Réserves BL-2026-000125',
      fileName: 'BL-2026-000125_v2_FINAL.pdf',
      mimeType: 'application/pdf',
      version: 2,
      status: DocumentStatus.FINAL,
      templateVersion: 'v2.1-2026',
      checksum: 'SHA256:4E07408562BEDB8B60CE05C1DECFE3AD',
      uploadedBy: 'Koné Aminata',
      createdAt: '2026-09-28 14:05',
    },
    {
      id: 'doc-005',
      organizationId: 'org-sogepro-ci',
      entityType: 'INVOICE',
      entityId: 'inv-2026-0088',
      entityReference: 'FAC-2026-000088',
      documentType: DocumentType.INVOICE,
      title: 'Facture Définitive FAC-2026-000088 — GHU Lagunes',
      fileName: 'FAC-2026-000088_FINAL.pdf',
      mimeType: 'application/pdf',
      version: 1,
      status: DocumentStatus.FINAL,
      templateVersion: 'v2.0-2026',
      checksum: 'SHA256:EF2D127DE37B942BAAD06145E54B0C61',
      uploadedBy: 'N’Guessan Clarisse',
      createdAt: '2026-09-19 09:30',
    },
  ],
  invoices: [
    {
      id: 'inv-2026-0087',
      organizationId: 'org-sogepro-ci',
      reference: 'FAC-2026-000087',
      customerId: 'cust-collectivite-sud',
      contractId: 'ctr-2026-dcass-03',
      issueDate: '2026-08-10',
      dueDate: '2026-09-10', // Échue depuis 27 jours !
      status: InvoiceStatus.OVERDUE,
      subtotal: 6840000,
      taxAmount: 0,
      totalAmount: 6840000,
      paidAmount: 2840000,
      remainingAmount: 4000000,
      taxCertificationStatus: TaxCertificationStatus.CERTIFIED,
      taxCertificationRef: 'CERT-SANDBOX-2026-0887',
      notes: 'Solde de 4 000 000 FCFA en dépassement d’échéance (relance comptable effectuée).',
    },
    {
      id: 'inv-2026-0088',
      organizationId: 'org-sogepro-ci',
      reference: 'FAC-2026-000088',
      customerId: 'cust-chu-nord',
      contractId: 'ctr-2026-chu-01',
      deliveryId: 'del-2026-00124',
      issueDate: '2026-09-19',
      dueDate: '2026-11-03',
      status: InvoiceStatus.PARTIALLY_PAID,
      subtotal: 14900000,
      taxAmount: 0,
      totalAmount: 14900000,
      paidAmount: 10000000,
      remainingAmount: 4900000,
      taxCertificationStatus: TaxCertificationStatus.CERTIFIED,
      taxCertificationRef: 'CERT-SANDBOX-2026-0888',
      notes: 'Facture établie sur la base du BL-2026-000124 et du PV de réception signé.',
    },
    {
      id: 'inv-2026-0089',
      organizationId: 'org-sogepro-ci',
      reference: 'FAC-2026-000089',
      customerId: 'cust-crous-ci',
      contractId: 'ctr-2026-orciu-02',
      deliveryId: 'del-2026-00125',
      issueDate: '2026-09-29',
      dueDate: '2026-11-28',
      status: InvoiceStatus.ISSUED,
      subtotal: 21052000, // Facturé uniquement sur les quantités acceptées (5600 kg haricot au lieu de 6000)
      taxAmount: 0,
      totalAmount: 21052000,
      paidAmount: 0,
      remainingAmount: 21052000,
      taxCertificationStatus: TaxCertificationStatus.SUBMITTED,
      notes:
        'Montant calculé strictement sur les quantités acceptées (exclusion des 400 KG de haricot refusés).',
    },
  ],
  payments: [
    {
      id: 'pay-2026-0030',
      organizationId: 'org-sogepro-ci',
      reference: 'REG-2026-000030',
      invoiceId: 'inv-2026-0087',
      customerId: 'cust-collectivite-sud',
      paymentDate: '2026-09-02',
      amount: 2840000,
      method: 'VIREMENT_TRESOR',
      bankReference: 'VIR-TRESOR-CI-882104',
      recordedBy: 'N’Guessan Clarisse',
    },
    {
      id: 'pay-2026-0031',
      organizationId: 'org-sogepro-ci',
      reference: 'REG-2026-000031',
      invoiceId: 'inv-2026-0088',
      customerId: 'cust-chu-nord',
      paymentDate: '2026-10-01',
      amount: 10000000,
      method: 'VIREMENT_BANCAIRE',
      bankReference: 'VIR-SGBCI-20261001-994',
      recordedBy: 'N’Guessan Clarisse',
    },
  ],
  expenses: [
    {
      id: 'exp-01',
      organizationId: 'org-sogepro-ci',
      reference: 'DEP-2026-000051',
      category: ExpenseCategoryType.TRANSPORT,
      label: 'Location camion 25T & péages livraison GHU Cocody (BL-2026-000124)',
      amount: 245000,
      expenseDate: '2026-09-18',
      contractId: 'ctr-2026-chu-01',
      deliveryId: 'del-2026-00124',
      status: 'PAID',
      recordedBy: 'N’Guessan Clarisse',
    },
    {
      id: 'exp-02',
      organizationId: 'org-sogepro-ci',
      reference: 'DEP-2026-000052',
      category: ExpenseCategoryType.HANDLING,
      label: 'Équipe dockers chargement/déchargement 530 colis (BL-2026-000124)',
      amount: 115000,
      expenseDate: '2026-09-18',
      contractId: 'ctr-2026-chu-01',
      deliveryId: 'del-2026-00124',
      status: 'PAID',
      recordedBy: 'Bamba Souleymane',
    },
    {
      id: 'exp-03',
      organizationId: 'org-sogepro-ci',
      reference: 'DEP-2026-000053',
      category: ExpenseCategoryType.FUEL,
      label: 'Dotation gasoil flotte livraison Campus Sud & Anyama',
      amount: 310000,
      expenseDate: '2026-09-28',
      contractId: 'ctr-2026-orciu-02',
      deliveryId: 'del-2026-00125',
      status: 'PAID',
      recordedBy: 'Bamba Souleymane',
    },
    {
      id: 'exp-04',
      organizationId: 'org-sogepro-ci',
      reference: 'DEP-2026-000054',
      category: ExpenseCategoryType.STORAGE,
      label: 'Traitement phytosanitaire préventif & palettes entrepôt Yopougon',
      amount: 420000,
      expenseDate: '2026-10-01',
      contractId: 'ctr-2026-orciu-02',
      status: 'PAID',
      recordedBy: 'Yao Franck Olivier',
    },
    {
      id: 'exp-05',
      organizationId: 'org-sogepro-ci',
      reference: 'DEP-2026-000055',
      category: ExpenseCategoryType.MAINTENANCE,
      label: 'Révision système freinage tracteur 9104-GT-01 (Convoi Bouaké)',
      amount: 185000,
      expenseDate: '2026-10-05',
      contractId: 'ctr-2026-dcass-03',
      deliveryId: 'del-2026-00128',
      status: 'PAID',
      recordedBy: 'Bamba Souleymane',
    },
  ],
  configurableRules: [
    {
      id: 'rule-01',
      code: 'RULE_QUOTA_STRICT_BLOCK',
      title: 'Blocage automatique des dépassements de reliquat contractuel',
      category: RuleCategory.CONTRACTUAL,
      value: 'ACTIVÉ (Dérogation réservée aux rôles OWNER / ADMIN / MANAGER avec motif obligatoire)',
      description:
        'Empêche toute validation de livraison dont la quantité cumulée dépasserait la quantité contractuelle autorisée.',
      isEditable: true,
    },
    {
      id: 'rule-02',
      code: 'RULE_RECEPTION_EXPLICIT',
      title: 'Séparation stricte Quantité Expédiée vs Quantité Acceptée',
      category: RuleCategory.INTERNAL,
      value: 'OBLIGATOIRE',
      description:
        'Une livraison expédiée ne diminue définitivement le reliquat exécuté et n’alimente la facturation qu’après enregistrement explicite de la réception.',
      isEditable: false,
    },
    {
      id: 'rule-03',
      code: 'RULE_TAX_CERTIFICATION_PROVIDER',
      title: 'Connecteur de Certification Fiscale Électronique (Abstraction FNE)',
      category: RuleCategory.FISCAL,
      value: 'MODE_ABSTRACTION_CONFIGURABLE',
      description:
        'Aucune règle fiscale ou API non vérifiée n’est codée en dur. L’entreprise configure son régime fiscal et le connecteur de certification applicable.',
      isEditable: true,
    },
    {
      id: 'rule-04',
      code: 'RULE_DOC_IMMUTABILITY',
      title: 'Verrouillage et Versioning des Bordereaux Finalisés (Statut FINAL)',
      category: RuleCategory.DOCUMENTARY,
      value: 'ACTIF (SHA-256 + Incrément de version obligatoire)',
      description:
        'Un bordereau de livraison au statut FINAL ne peut jamais être modifié silencieusement. Toute régénération crée une nouvelle version auditée.',
      isEditable: false,
    },
    {
      id: 'rule-05',
      code: 'RULE_SITE_ACCESS_CONFIG',
      title: 'Exigences documentaires et horaires de réception par site client',
      category: RuleCategory.ADMINISTRATIVE,
      value: 'PARAMÉTRABLE PAR ADRESSE DE LIVRAISON',
      description:
        'Les pièces justificatives et plages horaires sont définies par fiche site selon les instructions communiquées par chaque client institutionnel.',
      isEditable: true,
    },
  ],
  auditLogs: [
    {
      id: 'aud-01',
      organizationId: 'org-sogepro-ci',
      userId: 'usr-logistics-03',
      userName: 'Bamba Souleymane',
      userRole: RoleName.LOGISTICS,
      action: AuditActionType.DOCUMENT_FINALIZED,
      entity: 'DeliveryNote',
      entityId: 'BL-2026-000124',
      summary: 'Validation et gel du bordereau BL-2026-000124 (v1 FINAL) — GHU Lagunes Cocody',
      ipAddress: '10.0.14.22',
      createdAt: '2026-09-18 07:25',
    },
    {
      id: 'aud-02',
      organizationId: 'org-sogepro-ci',
      userId: 'usr-manager-02',
      userName: 'Koné Aminata',
      userRole: RoleName.MANAGER,
      action: AuditActionType.VALIDATE,
      entity: 'Reception',
      entityId: 'BL-2026-000125',
      summary:
        'Enregistrement réception partielle BL-2026-000125 : 400 KG Haricot Blanc refusés (retour stock quarantaine)',
      oldValue: '{"status":"DISPATCHED"}',
      newValue: '{"status":"PARTIALLY_RECEIVED","rejectedKg":400}',
      ipAddress: '10.0.14.18',
      createdAt: '2026-09-28 13:20',
    },
    {
      id: 'aud-03',
      organizationId: 'org-sogepro-ci',
      userId: 'usr-accounting-05',
      userName: 'N’Guessan Clarisse',
      userRole: RoleName.ACCOUNTING,
      action: AuditActionType.PAYMENT_RECORDED,
      entity: 'Invoice',
      entityId: 'FAC-2026-000088',
      summary:
        'Enregistrement encaissement REG-2026-000031 de 10 000 000 FCFA sur FAC-2026-000088 (Reste à recouvrer : 4 900 000 FCFA)',
      oldValue: '{"paidAmount":0,"remainingAmount":14900000}',
      newValue: '{"paidAmount":10000000,"remainingAmount":4900000}',
      ipAddress: '10.0.14.31',
      createdAt: '2026-10-01 15:12',
    },
    {
      id: 'aud-04',
      organizationId: 'org-sogepro-ci',
      userId: 'usr-logistics-03',
      userName: 'Bamba Souleymane',
      userRole: RoleName.LOGISTICS,
      action: AuditActionType.UPDATE,
      entity: 'Delivery',
      entityId: 'BL-2026-000126',
      summary:
        'Expédition du convoi BL-2026-000126 (Camion 4821-KJ-01) vers Annexe Régionale Nord Anyama',
      oldValue: '{"status":"READY"}',
      newValue: '{"status":"DISPATCHED"}',
      ipAddress: '10.0.14.22',
      createdAt: '2026-10-07 07:10',
    },
  ],
  sequences: {
    BL: 128,
    FAC: 89,
    CMD: 42,
    REG: 31,
    ACH: 19,
    DEP: 55,
  },
};
